# Generated by Django 3.2.16 on 2024-09-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240909_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
